onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver

overrides:
  '@eslint/eslintrc>ajv': ^6.12.4
  '@eslint/js': ^9
  '@stylistic/eslint-plugin': '>=5.0.0'
  '@types/node': ^24.10.4
  ajv@<8.18.0: '>=8.18.0'
  diff@<8.0.3: '>=8.0.3'
  esbuild@<=0.24.2: '>=0.27.0'
  eslint: ^9
  eslint>ajv: ^6.12.4
  glob@>=10.3.7 <=11.0.3: '>=11.1.0'
  minimatch@<10.2.1: '>=10.2.1'
  path-to-regexp@>=4.0.0 <6.3.0: '>=6.3.0'
  seroval@<1.4.1: '>=1.4.1'
  tar@<7.5.8: '>=7.5.8'
  tar@<=7.5.2: '>=7.5.3'
  undici@<5.29.0: '>=5.29.0'
