onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver

overrides:
  '@types/node': ^24.10.4
  diff@<8.0.3: '>=8.0.3'
  esbuild@<=0.24.2: '>=0.25.0'
  glob@>=10.3.7 <=11.0.3: '>=11.1.0'
  path-to-regexp@>=4.0.0 <6.3.0: '>=6.3.0'
  seroval@<1.4.1: '>=1.4.1'
  seroval@<=1.4.0: '>=1.4.1'
  tar@<=7.5.2: '>=7.5.3'
  undici@<5.29.0: '>=5.29.0'
  undici@>=4.5.0 <5.28.5: '>=5.28.5'
